---
title: "Demo of Quarto with webR v0.2.0"
format: html
engine: knitr
filters:
- webr
---

## sessionInfo()

This displays the installed packages and version of webR.

```{webr-r}
sessionInfo()
```

## Increased Package Availability

webR v0.2.0 has added about 51% of all CRAN packages. You can view them at the webR repo [here](https://repo.r-wasm.org/). Give this block a while to run.

```{webr-r}
webr::install("ggplot2")
library("ggplot2")
```

## Downloading csv files

Only certain URL's can be accessed by webR due to web browser security settings. However, raw files on Github are able to be accessed like in the following code cell. There is some more detail in [this](https://github.com/r-wasm/webr/issues/252#issuecomment-1685820473) Github comment.

```{webr-r}
download.file(
  "https://gist.githubusercontent.com/slopp/ce3b90b9168f2f921784de84fa445651/raw/4ecf3041f0ed4913e7c230758733948bc561f434/penguins.csv",
  "penguins.csv"
)
penguins <- read.csv("penguins.csv")
```

```{webr-r}
head(penguins)
```

## Graphing Demo

Install necessary packages

```{webr-r}
webr::install("palmerpenguins")
webr::install("ggthemes")
library(palmerpenguins)
library(ggthemes)
```

Make a graph, and edit it to see your changes!

```{webr-r}
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point(aes(color = species, shape = species)) +
  geom_smooth(method = "lm") +
  labs(
    title = "Body mass and flipper length",
    subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Flipper length (mm)", y = "Body mass (g)",
    color = "Species", shape = "Species"
  ) +
  scale_color_colorblind()
```

## Problems with `?` and `help()`

The default versions of these methods don't work, since they would typically open the help file in another window.

Here is an example of the error you would see

```{webr-r}
help(mean)
```

However, there is a workaround you can do by defining a new function to print the help file to the console. The source for this function is an R-bloggers post [here](https://www.r-bloggers.com/2013/06/printing-r-help-files-in-the-console-or-in-knitr-documents/).

```{webr-r}
help_console <- function(topic, format=c("text", "html", "latex", "Rd"),
                         lines=NULL, before=NULL, after=NULL) {  
  format=match.arg(format)
  if (!is.character(topic)) topic <- deparse(substitute(topic))
  helpfile = utils:::.getHelpFile(help(topic))

  hs <- capture.output(switch(format, 
                              text=tools:::Rd2txt(helpfile),
                              html=tools:::Rd2HTML(helpfile),
                              latex=tools:::Rd2latex(helpfile),
                              Rd=tools:::prepare_Rd(helpfile)
                              )
                      )
  if(!is.null(lines)) hs <- hs[lines]
  hs <- c(before, hs, after)
  cat(hs, sep="\n")
  invisible(hs)
}
```

```{webr-r}
help_console(mean)
```

## Empty code cell

```{webr-r}

```
